import multiprocessing

# The socket to bind. A string of the form: HOST, HOST:PORT, unix:PATH, fd://FD
# If gunicorn is run using systemd, take note that whatever is set here will be overriden by whatever
# is set in the ListenStream within the file gunicorn.socket.
bind = [
    # 'unix:/run/gunicorn.sock',
    # '0.0.0.0:8000',
    # '0.0.0.0:8001',
]

# Set environment variable (key=value).
# Pass variables to the execution environment.
# To put everything in 1 place, all environment variables are in EnvironmentFile of gunicorn.service file
raw_env = [
    # "SOME_VAR=SOME_VALUE",
]

# The number of worker processes for handling requests.
# A positive integer generally in the 2-4 x $(NUM_CORES) range.
workers = multiprocessing.cpu_count() * 2 + 1

# Detaches the server from the controlling terminal and enters the background.
# Similar effect with nohup or screen.
# Make sure that when using either of these service monitors (such as systemd) you do not enable the
# Gunicorn’s daemon mode. These monitors expect that the process they launch will be the process they
# need to monitor. Daemonizing will fork-exec which creates an unmonitored process and generally just
# confuses the monitor services.
daemon = False

# The Access log file to write to.
# '-' means log to stdout.
# Logs details of each HTTP Request made. The path is relative to where gunicorn will be invoked.
# Also see /var/log/nginx/access.log and /var/log/nginx/error.log
accesslog = 'log/accesslog.log'

# The access log format.
# access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
# Gunicorn 19 introduced a breaking change concerning how REMOTE_ADDR is handled. Previous to
# Gunicorn 19 this was set to the value of X-Forwarded-For if received from a trusted proxy.
# However, this was not in compliance with RFC 3875 which is why the REMOTE_ADDR is now the IP
# address of the proxy and not the actual user.
# To have access logs indicate the actual user IP when proxied, set access_log_format with a
# format which includes X-Forwarded-For. For example, this format uses X-Forwarded-For in place
# of REMOTE_ADDR:
#     %({x-forwarded-for}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
# It is also worth noting that the REMOTE_ADDR will be completely empty if you bind Gunicorn to
# a UNIX socket and not a TCP host:port tuple. So one way to populate it is by implementing a
# middleware that would assign it with the value in HTTP_X_FORWARDED_FOR
# "h" is the remote address specified in the HTTP Request header, specifically "request.META['REMOTE_ADDR']",
# but it is not anymore automatically populated thus the alternative "x-forwarded-for" is used which
# corresponds to "request.META['HTTP_X_FORWARDED_FOR']"
access_log_format = '%({x-forwarded-for}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'

# The Error log file to write to.
# Using '-' for FILE makes gunicorn log to stderr.
# Logs generated by Gunicorn starting from the loglevel provided and the higher levels.
errorlog = 'log/errorlog.log'

# The granularity of Error log outputs.
# Valid level names are:
#     debug
#     info
#     warning
#     error
#     critical
loglevel = 'info'

# Redirect stdout/stderr to specified file in errorlog.
# This catches prints made within Python code.
capture_output = True

# It is recommended to pass protocol information to Gunicorn. Many web frameworks use this information
# to generate URLs. Without this information, the application may mistakenly generate ‘http’ URLs in
# ‘https’ responses, leading to mixed content warnings or broken applications. To configure Nginx to
# pass an appropriate header, add a proxy_set_header directive to your location block:
#     ...
#     proxy_set_header X-Forwarded-Proto $scheme;
#     ...
# If you are running Nginx on a different host than Gunicorn you need to tell Gunicorn to trust the
# X-Forwarded-* headers sent by Nginx. By default, Gunicorn will only trust these headers if the
# connection comes from localhost. This is to prevent a malicious client from forging these headers:
#     $ gunicorn -w 3 --forwarded-allow-ips="10.170.3.217,10.170.3.220" test:app
# Front-end’s IPs from which allowed to handle set secure headers. (comma separate).
# Set to * to disable checking of Front-end IPs (useful for setups where you don’t know in advance the
# IP address of Front-end, but you still trust the environment). By default, the value of the
# FORWARDED_ALLOW_IPS environment variable. When the Gunicorn host is completely firewalled from the
# external network such that all connections come from a trusted proxy (e.g. Heroku) this value can be
# set to ‘*’. Using this value is potentially dangerous if connections to Gunicorn may come from
# untrusted proxies or directly from clients since the application may be tricked into serving SSL-only
# content over an insecure connection.
# If it is not defined, the default is "127.0.0.1".
# For multiple IPs, separate by comma such as "10.170.3.217,10.170.3.220"
forwarded_allow_ips = '127.0.0.1'
